[DIR]
arvi = E:\ADM IRC AND ZN\AR DEPO\Z MCO Automasi-AR-Orderan TEGAL\Dapur\ARClean_temp.xlsx

[MAP]
depo = SL|YY|MKS|MGL|PW|PWT|PLU|SG|SMG|TGL|PA|KDI

[AUTH]
secret_key = 

[BOT]
bot_token = 

[GENERAL]
gen_company_name = PT ABC
